default: db-constant.h db-constant.c db-enum.h db-struct.h db-io.h db-io.c db-btree.h db-btree.c db-engine.c
	gcc -Wall db-constant.h db-constant.c db-enum.h db-struct.h db-io.h db-io.c db-btree.h db-btree.c db-engine.c -o db-engine.o
